---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypyt-dep
  labels:
    app: mypyt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypyt
  template:
    metadata:
      labels:
        app: mypyt
    spec:
      containers:
      - name: mypyt
        image: ceetharamm/pyapp:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mypyt-svc
  labels:
    app: mypyt
spec:
  type: NodePort
  ports:
  - name: mypyt
    protocol: TCP
    port: 8089
    nodePort: 32123
    targetPort: 5000
  selector:
    app: mypyt
